# Generated by Django 5.2.6 on 2025-11-10 01:58

import datetime
import django.core.validators
import django.db.models.deletion
import events.utilities.file_handlers
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload event image.', null=True, upload_to=events.utilities.file_handlers.handle_event_file_upload)),
                ('title', models.CharField(help_text='Enter title for your event', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('small_description', models.TextField(blank=True, help_text='Small description about your event for search', null=True)),
                ('description', tinymce.models.HTMLField()),
                ('organiser', models.CharField(help_text="Enter organiser's full names or title", max_length=350)),
                ('start_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 11, 10, 1, 58, 2, 765655, tzinfo=datetime.timezone.utc), 'Event start date and time. It cannot be in the past')])),
                ('end_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 11, 10, 1, 58, 2, 765732, tzinfo=datetime.timezone.utc), 'Event end date and time. It cannot be in the past')])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the overall costs of this event', max_digits=10)),
                ('venue_name', models.CharField(help_text="Enter event's venue name", max_length=400)),
                ('address', models.CharField(blank=True, help_text='Enter event address separated by commas e.g. WaterFall Road 1234, Cape Town, WC, RSA', max_length=300, null=True)),
                ('phone', models.CharField(help_text="Enter event's cell/tele phone number", max_length=15, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('email', models.EmailField(blank=True, help_text="Enter event's email address for communications", max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text="Enter event's website starting with 'https://'", null=True)),
                ('map_coordinates', models.CharField(blank=True, max_length=300, null=True)),
                ('form_link', models.URLField(blank=True, help_text="Enter event's booking form link e.g Google Forms, start with https://", null=True)),
                ('status', models.CharField(choices=[('NOT APPROVED', 'Not approved'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='NOT APPROVED', max_length=50)),
                ('slots', models.PositiveIntegerField(default=4, help_text='Number of available player slots')),
                ('closing_date', models.DateField(help_text='Last date to confirm attendance')),
                ('dress_code_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_code_top', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_code_pants', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Admin costs for payment gateway', max_digits=6)),
                ('payment_required', models.BooleanField(default=True)),
                ('member_discount', models.DecimalField(decimal_places=2, default=50.0, help_text='Member discount in percentage (e.g. 50 for 50%)', max_digits=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('billing_name', models.CharField(max_length=100)),
                ('billing_surname', models.CharField(max_length=100)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_phone', models.CharField(max_length=15)),
                ('billing_address', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_note', models.TextField(blank=True, null=True)),
                ('inviter_full_names', models.CharField(blank=True, max_length=255, null=True)),
                ('inviter_member_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('EFT', 'EFT'), ('Cash on Arrival', 'Cash on Arrival'), ('Yoco', 'Yoco (Unavailable)')], default=('EFT', 'EFT'), max_length=30)),
                ('payment_status', models.CharField(choices=[('NOT APPROVED', 'Not approved'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='NOT APPROVED', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_referrence', models.CharField(db_index=True, editable=False, max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
