# Generated by Django 5.2.6 on 2025-11-10 01:55

import accounts.utilities.file_handlers
import accounts.utilities.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('slug', models.SlugField(default='about-ct-black-pro', max_length=300, unique=True)),
                ('operating_hours', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('address', models.CharField(blank=True, help_text='Add club main address e.g Central park, KZN, 7441', max_length=300, null=True, unique=True)),
                ('address_coordinates', models.CharField(blank=True, help_text='Add club main address coordinates separated by comma e.g 10.00,12.66', max_length=300, null=True)),
                ('number_of_members', models.IntegerField(default=0)),
                ('number_of_golf_holes', models.IntegerField(default=0)),
                ('number_of_golf_areas', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, help_text='Enter telephone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Enter other telephone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('facebook', models.URLField(blank=True, help_text='Enter facebook link e.g https://www.facebook.com/profile', null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, help_text='Enter twitter link e.g https://www.twitter.com/profile', null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, help_text='Enter instagram link e.g https://www.instagram.com/profile', null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, help_text='Enter linkedin link e.g https://www.linkedin.com/profile', null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True, unique=True)),
                ('mission', models.TextField(blank=True, null=True, unique=True)),
                ('club_profile', models.FileField(blank=True, help_text='Upload club profile', null=True, upload_to=accounts.utilities.file_handlers.handle_profile_upload)),
            ],
            options={
                'verbose_name': 'About Company',
                'verbose_name_plural': 'About Companys',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('profile_image', models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to=accounts.utilities.file_handlers.handle_profile_upload)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Cllr', 'Cllr'), ('Eng', 'Eng'), ('Dr', 'Dr'), ('Prof', 'Prof.')], default=('Mr', 'Mr'), max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male')], default='Male', help_text='Male Only Club', max_length=10)),
                ('race', models.CharField(choices=[('African', 'African'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('White', 'White'), ('Other', 'Other')], max_length=50)),
                ('membership_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('hna_membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True, help_text='Tell us a little bit about your professional or business.')),
                ('is_technical', models.BooleanField(default=False)),
                ('is_email_activated', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('Chairman', 'Chairman'), ('Public Relations Officer', 'Public Relations Officer'), ('Captain', 'Captain'), ('Vice Captain', 'Vice Captain'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Chairman Rules and Discipline', 'Chairman: Rules and Discipline Committee'), ('Member', 'General Member')], max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
