# Generated by Django 5.2.6 on 2025-11-10 01:55

import accounts.utilities.file_handlers
import accounts.utilities.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import memberships.utilities.handle_file
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to=accounts.utilities.file_handlers.handle_profile_upload)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Cllr', 'Cllr'), ('Eng', 'Eng'), ('Dr', 'Dr'), ('Prof', 'Prof.')], default=('Mr', 'Mr'), max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male')], default='Male', help_text='Male Only Club', max_length=10)),
                ('race', models.CharField(choices=[('African', 'African'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('White', 'White'), ('Other', 'Other')], max_length=50)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('hna_membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True, help_text='Tell us a little bit about your professional or business.')),
                ('application_number', models.CharField(db_index=True, max_length=250, unique=True)),
                ('membership_choice', models.CharField(choices=[('CPT', 'Cape Town Membership (R4500)'), ('COUNTRY', 'Country Membership (R2250)'), ('ESWATINI', 'Eswatini Membership (R1200.00)')], default='CPT', help_text='Choose Membership choice as seen on membership rates page', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of membership based on membership choice', max_digits=10)),
                ('status', models.CharField(choices=[('NOT_APPROVED', 'Not approved'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Awaiting Payment'), ('BLOCKED', 'Blocked')], default='NOT_APPROVED', help_text='Application status', max_length=50)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='MembershipEmail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=500)),
                ('task_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Membership Email',
                'verbose_name_plural': 'Membership Emails',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('Membership Joining Form', 'Membership Joining Form'), ('Membership Rates', 'Membership Rates'), ('Other', 'Other')], help_text='Choose a title for this file', max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('file', models.FileField(help_text='Upload membership file e.g Membership Joining Form or Membership Rates', upload_to=memberships.utilities.handle_file.handle_file_upload)),
                ('uploaded_by', models.ForeignKey(default=None, help_text='Select the author of this file e.g Your account', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='membership_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership File',
                'verbose_name_plural': 'Membership Files',
            },
        ),
    ]
